export const detalleProductos = [
    
    {   id: 1, 
        title: 'Game of Thrones' , 
        author: 'George R.R Martin',
        description:'Novela gráfica - Canción de Hielo y Fuego', 
        price: '$3000', 
        pictureUrl: "https://imagessl3.casadellibro.com/a/l/t5/93/9788466356893.jpg",
    },
    {   id: 2, 
        title: 'Harry Potter y la piedra filosofal', 
        author: 'J.K Rowling', 
        description: 'Novela gráfica - Primer volúmen', 
        price: '$2700', 
        pictureUrl: "https://imagessl8.casadellibro.com/a/l/t5/18/9788498386318.jpg",
    },
    {   id: 3, 
        title: 'El camino de los Reyes', 
        author: 'Brandon Sanderson', 
        description: 'Novela gráfica', 
        price: '$2600', 
        pictureUrl: "https://imagessl1.casadellibro.com/a/l/t5/41/9788413143941.jpg",
    },
    {   id: 4, 
        title: 'Galant', 
        author: 'V.E. SCHWAB', 
        description: 'Novela gráfica', 
        price: '$2400', 
        pictureUrl: "https://imagessl4.casadellibro.com/a/l/t5/64/9788416517664.jpg",
    }
]